apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollout
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary-rollouts-demo
        #image: particule/simplecolorapi:1.0
        image: ghcr.io/shclub/vue3:v2
        imagePullPolicy: Always
        env:
          - name: BACKEND_API_URL
            value: "backend"
        ports:
        - containerPort: 8080
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: canary-rollout
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
  type: NodePort
