# ArgoCD Blue/Green 배포 예제

apiVersion: argoproj.io/v1alpha1     # apps/v1 대신 argoproj.io/v1alpha1을 사용한다
kind: Rollout  # Deployment 대신 Rollout을 사용한다
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: frontend
        #image: argoproj/rollouts-demo:blue
        #image: argoproj/rollouts-demo:green
        #image: yyazi/vue_crud
        image: ghcr.io/shclub/vue3:v2
        imagePullPolicy: Always
        env:
          - name: BACKEND_API_URL
            value: "backend"
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      #activeService는 이전의 배포된 Blue 서비스
      activeService: frontend-service
      
      #previewService는 새롭게 배포될 Green 서비스
      previewService: frontend-service-preview
      
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: false

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: rollout-bluegreen
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-preview
spec:
  selector:
    app: rollout-bluegreen
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
  type: NodePort
