apiVersion: v1	
kind: Service	
metadata:	
  name: employee-frontend
  labels:
    app: employee-frontend
spec:	
  ports:	
  - port: 80	
    targetPort: 8080
    name: http
  selector:	
    app: employee-frontend
  type: NodePort
